/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "k8s.io/api/features/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// FeatureUseApplyConfiguration represents an declarative configuration of the FeatureUse type for use
// with apply.
type FeatureUseApplyConfiguration struct {
	ReportTime *v1.Time                    `json:"reportTime,omitempty"`
	Version    *string                     `json:"version,omitempty"`
	Enabled    *v1alpha1.FeatureEnablement `json:"enabled,omitempty"`
}

// FeatureUseApplyConfiguration constructs an declarative configuration of the FeatureUse type for use with
// apply.
func FeatureUse() *FeatureUseApplyConfiguration {
	return &FeatureUseApplyConfiguration{}
}

// WithReportTime sets the ReportTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReportTime field is set to the value of the last call.
func (b *FeatureUseApplyConfiguration) WithReportTime(value v1.Time) *FeatureUseApplyConfiguration {
	b.ReportTime = &value
	return b
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *FeatureUseApplyConfiguration) WithVersion(value string) *FeatureUseApplyConfiguration {
	b.Version = &value
	return b
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *FeatureUseApplyConfiguration) WithEnabled(value v1alpha1.FeatureEnablement) *FeatureUseApplyConfiguration {
	b.Enabled = &value
	return b
}
